/* Exact rational polynomial arithmetic. No executable student input. */
(function(root){'use strict';
const abs=n=>n<0n?-n:n;const gcd=(a,b)=>{a=abs(a);b=abs(b);while(b){[a,b]=[b,a%b]}return a||1n};
class Q{constructor(n,d=1n){n=BigInt(n);d=BigInt(d);if(!d)throw Error('Nulou nelze dělit.');if(d<0n){n=-n;d=-d}const g=gcd(n,d);this.n=n/g;this.d=d/g}add(b){return new Q(this.n*b.d+b.n*this.d,this.d*b.d)}neg(){return new Q(-this.n,this.d)}mul(b){return new Q(this.n*b.n,this.d*b.d)}div(b){return new Q(this.n*b.d,this.d*b.n)}eq(b){return this.n===b.n&&this.d===b.d}toString(){return this.d===1n?String(this.n):this.n+'/'+this.d}static from(s){s=String(s);if(s.includes('/')){const [a,b]=s.split('/');return Q.from(a).div(Q.from(b))}const [a,b='']=s.split('.');return new Q(BigInt(a+b),10n**BigInt(b.length))}}
const constant=q=>new Map(q.n?[['0,0',q]]:[]);const one=()=>constant(new Q(1));
function add(a,b,neg=false){const c=new Map(a);for(const[k,v]of b){const n=(c.get(k)||new Q(0)).add(neg?v.neg():v);if(n.n)c.set(k,n);else c.delete(k)}return c}
function mul(a,b){const c=new Map();for(const[ka,va]of a)for(const[kb,vb]of b){const pa=ka.split(',').map(Number),pb=kb.split(',').map(Number),k=[pa[0]+pb[0],pa[1]+pb[1]].join(',');if(pa[0]+pb[0]+pa[1]+pb[1]>24)throw Error('Použij mocniny nejvýše do 24. stupně.');const n=(c.get(k)||new Q(0)).add(va.mul(vb));if(n.n)c.set(k,n);else c.delete(k)}if(c.size>200)throw Error('Výraz je příliš rozsáhlý.');return c}
function normalize(s){if(typeof s!=='string'||s.length>400)throw Error('Použij kratší matematický zápis.');s=s.toLowerCase().replace(/[−–]/g,'-').replace(/[×·]/g,'*').replace(/[÷:]/g,'/').replace(/,/g,'.').replace(/\*\*/g,'^').replace(/[²³⁴⁵⁶⁷⁸⁹]/g,c=>'^'+('²³⁴⁵⁶⁷⁸⁹'.indexOf(c)+2)).replace(/[\[\{]/g,'(').replace(/[\]\}]/g,')');
// x2 / y3 are unambiguous only when the digit ends this factor.
s=s.replace(/([xy])([23])(?=\s*(?:[+\-*/^)]|$))/g,'$1^$2');if(/[xy]\s*\d/.test(s))throw Error('Mocninu piš jednoznačně: x^2. Násobení piš x*2.');return s}
function parse(s){s=normalize(s);const tokens=[];let i=0;while(i<s.length){if(/\s/.test(s[i])){i++;continue}const m=s.slice(i).match(/^(?:\d+(?:\.\d+)?|\.\d+)/);if(m){tokens.push({t:'n',v:m[0]});i+=m[0].length;continue}if(/[xy()+\-*/^]/.test(s[i])){tokens.push({t:s[i++]});continue}throw Error('Použij čísla, x, y, závorky a početní znaménka.')}if(!tokens.length)throw Error('Nejdřív napiš odpověď.');let p=0,depth=0;const peek=()=>tokens[p]?.t;const take=t=>{if(peek()!==t)throw Error('Zkontroluj závorky a početní znaménka.');return tokens[p++]};
function atom(){if(++depth>50)throw Error('Příliš mnoho vnořených závorek.');let n;if(peek()==='n')n={t:'n',v:take('n').v};else if(peek()==='x'||peek()==='y')n={t:'v',v:tokens[p++].t};else if(peek()==='('){take('(');n={t:'g',a:sum()};take(')')}else throw Error('Zkontroluj zápis výrazu.');depth--;return n}
function power(){let n=atom();if(peek()==='^'){take('^');n={t:'^',a:n,b:unary()}}return n}
function unary(){if(peek()==='+'||peek()==='-'){const op=tokens[p++].t;return{t:'u',op,a:unary()}}return power()}
function product(){let n=unary();while(peek()==='*'||peek()==='/'||peek()==='n'||peek()==='x'||peek()==='y'||peek()==='('){let op='*';if(peek()==='*'||peek()==='/')op=tokens[p++].t;n={t:op,a:n,b:unary()}}return n}
function sum(){let n=product();while(peek()==='+'||peek()==='-'){const op=tokens[p++].t;n={t:op,a:n,b:product()}}return n}
const n=sum();if(p!==tokens.length)throw Error('Zkontroluj závorky a početní znaménka.');return n}
function poly(n,vars={}){if(n.t==='n')return constant(Q.from(n.v));if(n.t==='v')return n.v in vars?constant(Q.from(vars[n.v])):new Map([[n.v==='x'?'1,0':'0,1',new Q(1)]]);if(n.t==='g')return poly(n.a,vars);if(n.t==='u'){const a=poly(n.a,vars);return n.op==='-'?mul(constant(new Q(-1)),a):a}const a=poly(n.a,vars),b=poly(n.b,vars);if(n.t==='+')return add(a,b);if(n.t==='-')return add(a,b,true);if(n.t==='*')return mul(a,b);if(n.t==='/'){if([...b.keys()].some(k=>k!=='0,0'))throw Error('Dělení proměnnou zde nepodporujeme.');const d=b.get('0,0')||new Q(0);return mul(a,constant(new Q(1).div(d)))}if(n.t==='^'){if([...b.keys()].some(k=>k!=='0,0'))throw Error('Exponent musí být celé nezáporné číslo.');const q=b.get('0,0')||new Q(0);if(q.d!==1n||q.n<0n||q.n>12n)throw Error('Zadej celý exponent od 0 do 12.');let out=one();for(let i=0;i<Number(q.n);i++)out=mul(out,a);return out}throw Error('Neznámá operace.');}
const equal=(a,b)=>a.size===b.size&&[...a].every(([k,v])=>b.get(k)?.eq(v));
function format(p){if(!p.size)return'0';const items=[...p].sort(([a],[b])=>{const aa=a.split(',').map(Number),bb=b.split(',').map(Number);return(bb[0]+bb[1])-(aa[0]+aa[1])||bb[0]-aa[0]});let s='';for(const[k,q]of items){const[x,y]=k.split(',').map(Number);const v=(x?'x'+(x>1?'^'+x:''):'')+(y?'y'+(y>1?'^'+y:''):'');const mag=new Q(abs(q.n),q.d);const c=mag.eq(new Q(1))&&v?'':mag.toString();s+=(s?(q.n<0n?' - ':' + '):(q.n<0n?'-':''))+c+v}return s}
function terms(n,sign=1,out=[]){if(n.t==='g')return terms(n.a,sign,out);if(n.t==='u')return terms(n.a,n.op==='-'?-sign:sign,out);if(n.t==='+'||n.t==='-'){terms(n.a,sign,out);terms(n.b,n.t==='-'?-sign:sign,out)}else out.push({n,sign});return out}
function simple(n){const list=terms(n),keys=[];for(const{n:t}of list){if(hasSum(t))return false;const p=poly(t);if(p.size!==1)return list.length===1&&p.size===0;if([...p.values()].some(q=>!q.n))return false;keys.push([...p.keys()][0]);if(complexTerm(t))return false}return new Set(keys).size===keys.length}
function hasSum(n){return n.t==='+'||n.t==='-'||(n.a&&hasSum(n.a))||(n.b&&hasSum(n.b))||false}
function complexTerm(n){if(n.t==='g')return true;if(n.t==='*'&&variables(n.a)&&variables(n.b)){const a=poly(n.a),b=poly(n.b);if(a.size!==1||b.size!==1)return true;const ka=[...a.keys()][0].split(',').map(Number),kb=[...b.keys()][0].split(',').map(Number);if(ka.some((v,i)=>v&&kb[i]))return true;}if(n.t==='^'&&n.a.t!=='v')return true;if((n.t==='*'||n.t==='/')&&!variables(n)&&!numberFinal(n))return true;return(n.a&&complexTerm(n.a))||(n.b&&complexTerm(n.b))||false}
const variables=n=>n.t==='v'||!!(n.a&&variables(n.a))||!!(n.b&&variables(n.b));const hasOperation=n=>['+','-','*','/','^'].includes(n.t);
function unwrap(n){while(n.t==='g'||n.t==='u'&&n.op==='+')n=n.a;return n}
function factorForm(n,p){n=unwrap(n);if(n.t!=='*')return false;let outside=poly(n.a),inside=poly(n.b),insideNode=n.b;if(outside.size!==1||inside.size<2){outside=poly(n.b);inside=poly(n.a);insideNode=n.a}if(outside.size!==1||inside.size<2)return false;const source=poly(parse(p.expression));const common=[...source.keys()].map(k=>k.split(',').map(Number));const powers=[Math.min(...common.map(v=>v[0])),Math.min(...common.map(v=>v[1]))];const coeff=[...source.values()];let num=0n,den=1n;for(const q of coeff){num=num===0n?abs(q.n):gcd(num,q.n);den=den*q.d/gcd(den,q.d)}const expected=new Q(num,den);const[k,q]=[...outside][0];return k===powers.join(',')&&new Q(abs(q.n),q.d).eq(expected)&&simple(unwrap(insideNode))&&inside.size===source.size}
function numberFinal(n){n=unwrap(n);const signed=a=>a.t==='n'||a.t==='u'&&a.op==='-'&&a.a.t==='n';if(signed(n))return true;if(n.t!=='/'||!signed(unwrap(n.a))||!signed(unwrap(n.b)))return false;const a=poly(n.a).get('0,0')||new Q(0),b=poly(n.b).get('0,0')||new Q(0);return a.d===1n&&b.d===1n&&gcd(a.n,b.n)===1n;}
function classify(input,p){try{const ast=parse(input),value=poly(ast,p.vars||{}),target=poly(parse(String(p.answer)));if(!equal(value,target))return{kind:'wrong'};if(p.goal==='number'){if(variables(ast))return{kind:'unchanged',message:'Nejprve dosaď zadané hodnoty za proměnné.'};return{kind:numberFinal(ast)?'done':'step'}}if(p.goal==='factor')return{kind:factorForm(ast,p)?'done':'step'};if(p.goal==='compose')return{kind:'done'};return{kind:simple(ast)?'done':normalize(input).replace(/\s/g,'')===normalize(p.expression).replace(/\s/g,'')?'unchanged':'step'}}catch(e){return{kind:'invalid',message:e.message}}}
function numericSteps(s){let n=parse(s);const list=[];function visit(a){if(a.t==='n')return a;if(a.t==='g'){const child=visit(a.a);return{t:'n',v:format(poly(child))}}if(a.t==='v')throw Error('Číselný výraz nesmí obsahovat proměnnou.');const b={...a,a:visit(a.a),...(a.b?{b:visit(a.b)}:{})};const q=format(poly(b));list.push({expression:print(b),answer:q});return{t:'n',v:q}}visit(n);return list}
function print(n){if(n.t==='n')return n.v.startsWith('-')?'('+n.v+')':n.v;if(n.t==='v')return n.v;if(n.t==='g')return'('+print(n.a)+')';if(n.t==='u')return n.op+print(n.a);return'('+print(n.a)+' '+n.t+' '+print(n.b)+')'}
const api={Q,parse,poly,equal,format,normalize,classify,simple,factorForm,numericSteps,print};if(typeof module!=='undefined')module.exports=api;root.ExpressionMath=api;
})(typeof globalThis!=='undefined'?globalThis:this);
