/* Family UI, persisted lessons/tasks, city, demos and local parent reports. */
(function(){'use strict';const M=ExpressionMath,C=ExpressionContent,City=ExpressionCity,$=id=>document.getElementById(id),kind=document.body.dataset.module,demo=/-demo\.html$/.test(location.pathname),LIMIT=18;
const KEY='fdc-expressions-v4-'+kind+(demo?'-demo':''),WORLD='fdc-expression-city-v4'+(demo?'-demo':''),AUTH='fdc-expression-parent-v4';const titles={num:'Číselné výrazy',var:'Výrazy s proměnnými',poly:'Mnohočleny'},levels=['Základní','Pokročilá','Výzva'];
const empty=()=>({done:0,right:0,first:0,wrong:0,hints:0,skips:0,cells:{},days:{},history:[],lessons:{},seen:[],selection:{topic:0,level:0,mode:'teach'},active:null});const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}};
let stats=Object.assign(empty(),read(KEY,null)),sel=stats.selection,task,attempt=0,hinted=false,finished=false,guideIndex=0,storageWarn=false,parentOpen=false,parentAuthorized=false;let prefs=read('fdc-expression-prefs',{sound:true,theme:'light',game:true});const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const visual=s=>String(s).replace(/\^([234])/g,(_,n)=>({'2':'²','3':'³','4':'⁴'}[n])).replace(/\*/g,' · ').replace(/-/g,'−').replace(/\.(\d)/g,',$1');
function store(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{if(!storageWarn){$('storageInfo').hidden=false;$('storageInfo').textContent='Prohlížeč nemůže ukládat postup. Povol ukládání dat pro tento web.';storageWarn=true}}}
function save(){stats.active=task?{task,attempt,hinted,finished,guideIndex,input:$('answer').value}:null;store(KEY,stats)}
function cell(){const key=sel.topic+'-'+sel.level;return stats.cells[key]||(stats.cells[key]={done:0,right:0,first:0,wrong:0,hints:0,skips:0})}
function lessonKey(){return sel.topic+'-'+sel.level}function lessonStage(){return stats.lessons[lessonKey()]||0}
function message(s,cls=''){$('feedback').textContent=s;$('feedback').className='feedback '+cls}
function sound(ok,unlock=false){if(!prefs.sound)return;try{const ctx=new(window.AudioContext||window.webkitAudioContext)(),base=ok?[392,440,523,587][stats.right%4]:170;[0,ok?4:-2,unlock?12:7].forEach((n,i)=>{const o=ctx.createOscillator(),g=ctx.createGain(),t=ctx.currentTime+i*.09;o.frequency.value=base*2**(n/12);o.type='sine';g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(.035,t+.01);g.gain.exponentialRampToValueAtTime(.001,t+.17);o.connect(g);g.connect(ctx.destination);o.start(t);o.stop(t+.18)});setTimeout(()=>ctx.close(),700)}catch{}}
function world(){const data=read(WORLD,{points:0,modules:{}}),p=data.points;$('world').innerHTML=City.scene(p);const index=Math.floor(p%150/10),cycle=Math.floor(p/150);$('worldProgress').textContent=`Etapa ${Math.floor(p/150)+1} · ${p} bodů obnovy · ${index}/15 staveb v provozu`;$('worldBar').style.width=(p%10*10)+'%';$('nextReward').textContent=(cycle?'Rozšíření '+(cycle+1)+': ':'')+City.stages[index];$('rewardDetail').textContent=`Do obnovy zbývá ${10-p%10} správně dokončených úloh.`;$('worldNote').textContent=demo?'Ukázkové město je společné pro všechna tři dema.':'Město je společné pro všechny tři moduly v tomto prohlížeči. Po festivalu následuje nová etapa obnovy s novými úlohami.';$('stat').textContent=`Dokončeno ${stats.done} · správně ${stats.right}`;document.body.classList.toggle('game-off',!prefs.game);}
function lesson(){const l=C.lessons[kind][sel.topic],st=lessonStage();$('lesson').hidden=sel.mode!=='teach';$('lessonTitle').textContent=l[1];$('lessonRule').textContent=l[2];const sample=C.generate(kind,sel.topic,sel.level,310987);$('sample').innerHTML='<b>Vyřešený vzor</b><p>'+esc(sample.prompt)+' '+esc(visual(sample.expression))+(sample.vars?' · '+esc(Object.entries(sample.vars).map(([v,n])=>v+' = '+visual(n)).join(', ')):'')+'</p><ol>'+sample.steps.map(s=>'<li>'+esc(visual(s))+'</li>').join('')+'</ol><b>'+esc(visual(sample.answer))+'</b>';$('sample').hidden=st>0;$('sampleToggle').textContent=st>0?'Ukázat vyřešený vzor':'Skrýt vyřešený vzor';$('phase').textContent=sel.mode==='teach'?['1/4 · Pravidlo a vzor. Teď zkus vedený úkol.','2/4 · Samostatný úkol. Použij naučené pravidlo.','3/4 · Ověření porozumění. Nová varianta bez vedení.','4/4 · Princip ověřen. Můžeš pokračovat nebo přejít na procvičování.'][Math.min(3,st)]:'Samostatné procvičování · všechny typy jsou volně přístupné.';}
function draw(reset=true){$('topic').value=sel.topic;$('level').value=sel.level;$('teach').classList.toggle('chosen',sel.mode==='teach');$('practice').classList.toggle('chosen',sel.mode==='practice');lesson();$('expression').textContent=visual(task.expression);$('variables').textContent=task.vars?Object.entries(task.vars).map(([v,n])=>v+' = '+visual(n)).join(', '):'';$('rule').textContent=task.prompt;if(sel.mode==='teach'&&lessonStage()===0&&kind==='num'&&!finished){const s=M.numericSteps(task.expression)[guideIndex];if(s)$('rule').textContent='Vedený krok '+(guideIndex+1)+': vypočítej '+visual(s.expression)+'. Můžeš zadat i konečný výsledek.'}
if(sel.mode==='teach'&&lessonStage()===0&&kind!=='num'&&!finished){$('rule').textContent=task.prompt+' Vedení: '+task.hint+' Zapiš první úpravu nebo konečnou odpověď.'}
$('answer').disabled=finished;$('check').hidden=finished;$('next').hidden=!finished;$('hint').hidden=finished;$('skip').hidden=finished;$('explain').hidden=!finished;if(finished)showSolution();else if(reset){$('answer').value='';message('')}$('exercise').hidden=parentOpen;$('demoEnd').hidden=!(demo&&stats.done>=LIMIT&&!task);world();if(!finished&&!parentOpen)$('answer').focus({preventScroll:true});}
function next(){if(demo&&stats.done>=LIMIT){task=null;save();$('exercise').hidden=true;$('demoEnd').hidden=false;world();return}let p;for(let i=0;i<30;i++){const seed=crypto.getRandomValues(new Uint32Array(1))[0];p=sel.mode==='teach'&&lessonStage()===2?C.verify(kind,sel.topic,sel.level,seed):C.generate(kind,sel.topic,sel.level,seed);if(!stats.seen.includes(p.expression))break}task=p;attempt=0;hinted=false;finished=false;guideIndex=0;stats.seen.push(p.expression);stats.seen=stats.seen.slice(-150);draw();save();}
function showSolution(){$('explain').innerHTML='<strong>Postup řešení</strong><ol>'+task.steps.map(s=>'<li>'+esc(visual(s))+'</li>').join('')+'</ol><b>Výsledek: '+esc(visual(task.answer))+'</b>';}
function finish(ok,skip=false){if(finished)return;finished=true;const c=cell();stats.done++;c.done++;if(ok){stats.right++;c.right++;if(!attempt&&!hinted){stats.first++;c.first++}if(sel.mode==='teach'&&!hinted&&!attempt)stats.lessons[lessonKey()]=Math.min(3,lessonStage()+1);const w=read(WORLD,{points:0,modules:{}});w.points++;w.modules[kind]=(w.modules[kind]||0)+1;store(WORLD,w);const event=w.points%10===0;$('worldEvent').textContent=event?'Obnoveno: '+City.stages[(Math.floor((w.points-1)%150/10))]+'!':'Město získalo další bod obnovy.';sound(true,event)}else if(skip){stats.skips++;c.skips++}const date=new Date().toLocaleDateString('sv-SE');stats.days[date]=(stats.days[date]||0)+1;stats.history.unshift({date,topic:sel.topic,level:sel.level,ok,skip,wrong:attempt,hint:hinted,expression:task.expression});stats.history=stats.history.slice(0,250);draw(false);message(ok?'Správně dokončeno! Pokračuj klávesou Enter.':skip?'Úloha přeskočena. Projdi si postup a pokračuj.':'Tady je postup řešení. Další podobný příklad ti pomůže pravidlo upevnit.',ok?'good':'');$('next').focus();save();banner();}
function check(){if(finished){next();return}const raw=$('answer').value.trim();if(!raw){message('Nejdřív napiš odpověď.');return}let result=M.classify(raw,task);if(result.kind==='wrong'&&!task.concept&&(kind==='num'||task.vars)){try{let expression=task.expression;if(task.vars)expression=expression.replace(/[xy]/g,v=>'('+task.vars[v]+')').replace(/(\d)\(/g,'$1*(');const s=M.numericSteps(expression),v=M.poly(M.parse(raw)),index=s.findIndex((step,i)=>i>=guideIndex&&M.equal(v,M.poly(M.parse(step.answer))));if(index>=0){guideIndex=index+1;if(guideIndex>=s.length){finish(true);return}draw(false);message('Správný mezivýsledek. Pokračuj k hodnotě celého výrazu.','good');$('answer').value='';save();return}}catch{}}
if(result.kind==='done'){finish(true);return}if(result.kind==='step'||result.kind==='unchanged'){message(result.message||(result.kind==='unchanged'?'Výraz jsi správně přepsal, ale úpravu je potřeba ještě provést.':task.goal==='factor'?'Výraz je ekvivalentní. Ještě vytkni největší společný činitel a uprav závorku.':task.goal==='number'?'Správný postup. Ještě dokonči výpočet; zlomek zkrať.':'Správný mezikrok! Ještě odstraň závorky a sluč podobné členy.'),'good');save();return}
if(result.kind==='invalid'){message(result.message,'warn');return}attempt++;stats.wrong++;cell().wrong++;save();sound(false);if(attempt===1)message('To ještě nesedí. Oprav postup a zkus to znovu.','warn');else if(attempt===2)message('Podívej se na zadání. Nabízím nápovědu k postupu.','warn');else if(!hinted)hint();else finish(false);}
function hint(){if(finished)return;if(!hinted){hinted=true;stats.hints++;cell().hints++;save()}message('Nápověda: '+task.hint,'warn');}
function change(){if(demo&&stats.done>=LIMIT){next();return}sel.topic=Number($('topic').value);sel.level=Number($('level').value);stats.selection=sel;next()}
function banner(){if(!demo)return;$('demoCounter').textContent=`Veřejná ukázka · ${stats.done}/${LIMIT} úloh · všechny oblasti a obtížnosti k vyzkoušení. Postup se ukládá.`;}
async function derive(password,salt){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const hash=await crypto.subtle.deriveBits({name:'PBKDF2',salt:Uint8Array.from(salt),iterations:180000,hash:'SHA-256'},key,256);return Array.from(new Uint8Array(hash))}
function openParent(){parentOpen=true;parentAuthorized=false;$('parent').hidden=false;$('exercise').hidden=true;$('parentActions').hidden=true;$('parentData').innerHTML='';$('parentPassword').value='';$('parentLogin').hidden=demo;if(demo){$('parentInfo').textContent='V plné verzi rodiče uvidí úspěšnost, chybné pokusy, nápovědy, přeskočené úlohy, vývoj po dnech a výsledky podle oblastí a obtížností. Mohou spustit cílené procvičování a po potvrzení vynulovat statistiky.';return}$('parentInfo').textContent=read(AUTH,null)?'Zadej rodičovské heslo.':'Nastav společné rodičovské heslo pro všechny tři moduly (alespoň 6 znaků).';}
async function authorize(){if(demo)return;const password=$('parentPassword').value;if(password.length<6){$('parentInfo').textContent='Použij alespoň 6 znaků.';return}const stored=read(AUTH,null);$('parentUnlock').disabled=true;try{if(stored){const hash=await derive(password,stored.salt);if(JSON.stringify(hash)!==JSON.stringify(stored.hash)){$('parentInfo').textContent='Nesprávné rodičovské heslo.';return}}else{const salt=Array.from(crypto.getRandomValues(new Uint8Array(16)));store(AUTH,{salt,hash:await derive(password,salt)})}parentAuthorized=true;$('parentPassword').value='';$('parentLogin').hidden=true;$('parentActions').hidden=false;$('parentInfo').textContent='Rodičovská sekce odemčena.';report()}catch{$('parentInfo').textContent='Heslo lze nastavit jen v prohlížeči s podporou šifrování přes HTTPS.'}finally{$('parentUnlock').disabled=false}}
function report(){if(!parentAuthorized)return;const attempted=stats.history.filter(h=>!h.skip).length;const rate=stats.done-stats.skips?Math.round(stats.right/(stats.done-stats.skips)*100):0;let html=`<p>Dokončeno <b>${stats.done}</b> · správně <b>${stats.right}</b> · úspěšnost <b>${rate} %</b> · napoprvé <b>${stats.first}</b><br>Chybné pokusy <b>${stats.wrong}</b> · nápovědy <b>${stats.hints}</b> · přeskočeno <b>${stats.skips}</b></p><div class="tablewrap"><table><thead><tr><th>Oblast / obtížnost</th><th>Správně / dokončeno</th><th>Chyby</th><th>Nápovědy</th><th>Přeskočeno</th><th>Procvičit</th></tr></thead><tbody>`;const weak=[];for(const[k,c]of Object.entries(stats.cells)){const[t,l]=k.split('-').map(Number);if(!C.lessons[kind][t])continue;html+=`<tr><td>${esc(C.lessons[kind][t][1])} / ${levels[l]}</td><td>${c.right} / ${c.done}</td><td>${c.wrong}</td><td>${c.hints}</td><td>${c.skips}</td><td><button data-target="${k}">Procvičit</button></td></tr>`;if(c.wrong>=2||c.done-c.skips-c.right>=2)weak.push(C.lessons[kind][t][1]+' ('+levels[l]+')')}
html+='</tbody></table></div><p><b>Oblasti k upevnění:</b> '+(weak.length?esc(weak.join(', ')):'Zatím nemáme dost výsledků pro doporučení.')+'</p><h3>Pokrok po dnech</h3><p>'+Object.entries(stats.days).sort().slice(-30).map(([d,n])=>esc(d)+': '+n+' úloh').join(' · ')+'</p><h3>Poslední úlohy</h3><ol>'+stats.history.slice(0,10).map(h=>'<li>'+esc(h.date+' · '+visual(h.expression)+' · '+(h.skip?'přeskočeno':h.ok?'správně':'s ukázaným řešením'))+'</li>').join('')+'</ol><p class="muted">Úspěšnost počítá dokončené úlohy bez přeskočených. Správně dokončená úloha může obsahovat opravu. Statistiky a heslo platí jen pro tento prohlížeč. Heslo omezuje běžný přístup dítěte; správce zařízení může místní data změnit nebo smazat.</p>';$('parentData').innerHTML=html;$('parentData').querySelectorAll('[data-target]').forEach(b=>b.onclick=()=>{const[t,l]=b.dataset.target.split('-').map(Number);sel={topic:t,level:l,mode:'practice'};stats.selection=sel;closeParent();next()});}
function closeParent(){parentOpen=false;parentAuthorized=false;$('parent').hidden=true;$('parentData').innerHTML='';$('parentActions').hidden=true;if(demo&&stats.done>=LIMIT&&!task){$('demoEnd').hidden=false}else if(task){draw(false)}else next()}
function reset(){if(!parentAuthorized||!confirm('Opravdu smazat statistiky a výukový pokrok tohoto modulu? Město zůstane zachované.'))return;stats=empty();sel=stats.selection;task=null;save();report();world()}
function init(){// Import the old counters once; current schemas stay distinct.
if(!localStorage.getItem(KEY)){const oldKey=kind==='num'?(demo?'fdc-vyrazy-demo-v3':'fdc-vyrazy-v3'):'fdc-algebra-'+(kind==='poly'?'poly':'var')+(demo?'-demo':'');const old=read(oldKey,null);if(old){stats.done=old.done||0;stats.right=old.right||0;stats.hints=old.hints||0;stats.skips=old.skips||0;stats.wrong=old.incorrectAttempts||0;const w=read(WORLD,{points:0,modules:{}});if(!w.modules[kind]){w.points+=stats.right;w.modules[kind]=stats.right;store(WORLD,w)}}}
if(!Number.isInteger(sel.topic)||!C.lessons[kind][sel.topic])sel.topic=0;if(![0,1,2].includes(sel.level))sel.level=0;if(!['teach','practice'].includes(sel.mode))sel.mode='teach';$('topic').innerHTML=C.lessons[kind].map((l,i)=>`<option value="${i}">${esc(l[1])}</option>`).join('');$('level').innerHTML=levels.map((l,i)=>`<option value="${i}">${l}</option>`).join('');$('topic').onchange=change;$('level').onchange=change;$('teach').onclick=()=>{sel.mode='teach';change()};$('practice').onclick=()=>{sel.mode='practice';change()};$('lessonRestart').onclick=()=>{stats.lessons[lessonKey()]=0;next()};$('sampleToggle').onclick=()=>{$('sample').hidden=!$('sample').hidden;$('sampleToggle').textContent=$('sample').hidden?'Ukázat vyřešený vzor':'Skrýt vyřešený vzor'};
$('check').onclick=check;$('next').onclick=next;$('hint').onclick=hint;$('skip').onclick=()=>finish(false,true);$('power').onclick=()=>{const e=$('answer'),start=e.selectionStart,end=e.selectionEnd;e.setRangeText('^2',start,end,'end');e.focus();save()};$('answer').oninput=save;document.addEventListener('keydown',e=>{if(e.key!=='Enter'||parentOpen)return;if(e.target===$('answer')||e.target===document.body||finished&&e.target===$('next')){e.preventDefault();finished?next():check()}});$('parentButton').onclick=openParent;$('parentClose').onclick=closeParent;$('parentUnlock').onclick=authorize;$('parentPassword').onkeydown=e=>{if(e.key==='Enter')authorize()};$('parentReset').onclick=reset;
function appearance(){document.body.dataset.theme=prefs.theme;$('sound').textContent=prefs.sound?'Zvuk: zapnutý':'Zvuk: vypnutý';$('game').textContent=prefs.game?'Hra: zapnutá':'Hra: vypnutá'}$('theme').onclick=()=>{prefs.theme=['light','dark','plum'][(['light','dark','plum'].indexOf(prefs.theme)+1)%3];store('fdc-expression-prefs',prefs);appearance()};$('sound').onclick=()=>{prefs.sound=!prefs.sound;store('fdc-expression-prefs',prefs);appearance()};$('game').onclick=()=>{prefs.game=!prefs.game;store('fdc-expression-prefs',prefs);appearance();world()};appearance();$('demoBanner').hidden=!demo;banner();const active=stats.active;if(active&&active.task?.kind===kind&&active.task.topic===sel.topic&&active.task.level===sel.level){task=active.task;attempt=active.attempt||0;hinted=!!active.hinted;finished=!!active.finished;guideIndex=active.guideIndex||0;draw(false);$('answer').value=active.input||'';if(finished)message('Úloha dokončena. Pokračuj klávesou Enter.','good')}else next();window.ExpressionApp={getState:()=>({stats,sel,task,attempt,hinted,finished,guideIndex}),check,next,hint,finish};}
init();window.addEventListener('storage',e=>{if(e.key===WORLD)world()});})();
