'use strict';const assert=require('node:assert/strict'),M=require('../vyrazy-math'),A=require('../algebra-core'),C=require('../vyrazy-content');
for(const s of ['x²','x^2','x**2','x2'])assert(A.equivalent(s,'x*x'),s);for(const s of ['x³','x^3','x**3','x3'])assert(A.equivalent(s,'x*x*x'),s);
for(const [a,b]of [['-3^2','-9'],['(-3)^2','9'],['2^3^2','512'],['1/3+1/6','1/2'],['0,1+0.2','3/10'],['2(x+3)','2x+6'],['x(x+1)','x²+x'],['(x+y)^2','x^2+2xy+y^2']])assert(A.equivalent(a,b),a);
assert(!A.equivalent('x*(x+1)*(x+3)*(x-2)*(x-5)','0'),'Do not sample only fixed points');
for(const s of ['alert(1)','globalThis','constructor','1/0','x/0','x/x','x^-1','x^13','x23','x 2','2..3','(()','2;3','<img>'])assert.throws(()=>M.poly(M.parse(s)),undefined,s);
const p={goal:'simplify',expression:'3x+4x',answer:'7x'};for(const s of ['3x+4x','2x+5x','7(x)'])assert(['step','unchanged'].includes(M.classify(s,p).kind),s);assert.equal(M.classify('7x',p).kind,'done');assert.equal(M.classify('8x',p).kind,'wrong');
const f={goal:'factor',expression:'6x²+9x',answer:'3x(2x+3)'};assert.equal(M.classify(f.answer,f).kind,'done');for(const s of ['6x²+9x','x(6x+9)','1(6x²+9x)','3x(x+x+3)','(3x)(x+x+3)','3x*(2x+3)'])assert.equal(M.classify(s,f).kind,s==='3x*(2x+3)'?'done':'step',s);
for(const s of ['5/6','0.8333333333333333'])assert.equal(M.classify(s,{goal:'number',answer:'5/6'}).kind,s==='5/6'?'done':'wrong');for(const s of ['10/12','1/2+1/3','-(2*3)'])assert.equal(M.classify(s,{goal:'number',answer:s==='-(2*3)'?'-6':'5/6'}).kind,'step');
assert.equal(M.classify('x²-2x',{goal:'number',vars:{x:'-3'},answer:'15'}).kind,'unchanged');assert.equal(M.classify('(-3)^2-2*(-3)',{goal:'number',vars:{x:'-3'},answer:'15'}).kind,'step');
for(const s of ['5xy','3x^2y','-4x^2y^2+7xy+2','1/2x+3/4'])assert.equal(M.classify(s,{goal:'simplify',expression:'',answer:s}).kind,'done',s);
const school={goal:'simplify',expression:'3(x+2)+2y-5(x+y)-2x+6y',answer:'-4x+3y+6'};
assert.equal(M.classify('3x+6+2y-5x-5y-2x+6y',school).kind,'step');assert.equal(M.classify('(3-5-2)x+(2-5+6)y+6',school).kind,'step');assert.equal(M.classify('-4x+3y+6',school).kind,'done');assert.equal(M.classify('6',school).kind,'wrong');assert.equal(C.example('var',0,0).expression,school.expression);
const identity={goal:'identityFactor',expression:'4x^2-9y^2',answer:'(2x-3y)(2x+3y)'};assert.equal(M.classify(identity.answer,identity).kind,'done');assert.equal(M.classify('(2x+3y)(2x-3y)',identity).kind,'done');assert.equal(M.classify('4x^2-9y^2',identity).kind,'step');assert.equal(M.classify('1*(4x^2-9y^2)',identity).kind,'step');
for(const [input,result]of [['(x+y)^2','x^2+2xy+y^2'],['(2x-3y)^2','4x^2-12xy+9y^2'],['(2x-3y)(2x+3y)','4x^2-9y^2'],['2(x-(3y-x))-(x+y)','3x-7y']]){const d=C.algebraDerivation(input);for(const step of [d.expanded,d.grouped,d.answer])assert(A.equivalent(step,result),step)}
// Independently interpret the parsed AST using number arithmetic, for test oracles only.
function independent(n,vars={}){if(n.t==='n')return Number(n.v);if(n.t==='v')return vars[n.v];if(n.t==='g')return independent(n.a,vars);if(n.t==='u')return(n.op==='-'?-1:1)*independent(n.a,vars);const a=independent(n.a,vars),b=independent(n.b,vars);return({'+':()=>a+b,'-':()=>a-b,'*':()=>a*b,'/':()=>a/b,'^':()=>a**b})[n.t]()}
let count=0,min=Infinity;for(const kind of Object.keys(C.lessons))for(let t=0;t<C.lessons[kind].length;t++)for(let l=0;l<3;l++){const unique=new Set();for(let i=0;i<1000;i++){const seed=(Math.imul(i+1,2654435761))>>>0,p=C.generate(kind,t,l,seed);count++;unique.add(p.expression);if(kind!=='num'){assert(!p.vars);assert(['simplify','factor','identityFactor'].includes(p.goal));const v=C.verify(kind,t,l,seed);assert(['simplify','factor','identityFactor'].includes(v.goal),'Algebra verification must remain symbolic');}assert.equal(M.classify(p.answer,p).kind,'done',JSON.stringify(p));assert(!JSON.stringify(p).includes('undefined'));assert(p.steps.length);if(p.goal==='number'&&!['terms','degree'].includes(C.lessons[kind][t][0])){const a=independent(M.parse(p.expression),Object.fromEntries(Object.entries(p.vars||{}).map(([k,v])=>[k,Number(v)]))),b=independent(M.parse(p.answer));assert(Math.abs(a-b)<1e-8*(1+Math.abs(b)),p.expression)}else if(p.goal!=='number'){for(const vars of [{x:-2,y:3},{x:0,y:1},{x:4,y:-1}]){const a=independent(M.parse(p.expression),vars),b=independent(M.parse(p.answer),vars);assert(Math.abs(a-b)<1e-7*(1+Math.abs(b)),p.expression)}}else{const coeff=M.poly(M.parse(p.expression));if(C.lessons[kind][t][0]==='degree')assert.equal(Number(p.answer),Math.max(...[...coeff.keys()].map(k=>k.split(',').map(Number).reduce((a,b)=>a+b))));else{const key=l===0?'1,0':l===1?'2,0':'1,2';assert.equal(p.answer,coeff.get(key).toString())}}}min=Math.min(min,unique.size);assert(unique.size>=200,kind+'/'+t+'/'+l+': '+unique.size)}console.log(`PASS: exact arithmetic regressions, input safety, goal validation; ${count} generated exercises; minimum ${min} unique variants per topic/difficulty.`);
