import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import fs from 'node:fs';
const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox','--no-zygote','--disable-dev-shm-usage']});
const base=process.env.BASE_URL||'http://127.0.0.1:8123/';const names=['vyrazy','vyrazy-promenne','mnohocleny'];fs.mkdirSync('test-results',{recursive:true});let solved=0;const errors=[];
async function solve(page){const answer=await page.evaluate(()=>ExpressionApp.getState().task.answer);await page.locator('#answer').fill(answer);await page.locator('#answer').press('Enter');assert(await page.locator('#next').isVisible());solved++;}
try{
for(const name of names){const ctx=await browser.newContext({viewport:{width:390,height:844}}),page=await ctx.newPage();page.on('pageerror',e=>errors.push(name+': '+e.message));await page.goto(base+name+'-demo.html');await page.locator('#answer').waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'mobile overflow '+name);await page.screenshot({path:'test-results/'+name+'-mobile.png',fullPage:true});assert(await page.locator('#lesson').isVisible());assert.match(await page.locator('#sample').textContent(),/Vyřešený vzor/);await page.locator('#practice').click();assert.equal(await page.locator('#lesson').isVisible(),false);await page.locator('#answer').fill('123');await page.reload();assert.equal(await page.locator('#answer').inputValue(),'123');await page.locator('#parentButton').click();assert.match(await page.locator('#parentInfo').textContent(),/V plné verzi/);assert.equal(await page.locator('#parentLogin').isVisible(),false);await page.locator('#parentClose').click();
for(let i=0;i<18;i++){await solve(page);await page.keyboard.press('Enter')};assert(await page.locator('#demoEnd').isVisible());await page.reload();assert(await page.locator('#demoEnd').isVisible());await page.locator('#parentButton').click();await page.locator('#parentClose').click();assert(await page.locator('#demoEnd').isVisible());await ctx.close();}
// Direct entry must redirect to each public demo; no authorized session is supplied.
for(const name of [...names,'vyrazy-rozcestnik']){const ctx=await browser.newContext(),p=await ctx.newPage();await p.goto(base+name+'.html');await p.waitForURL('**/'+name+'-demo.html');assert.equal(await p.evaluate(()=>getComputedStyle(document.documentElement).visibility),'visible');await ctx.close()}
const ctx=await browser.newContext({viewport:{width:1440,height:1000}});await ctx.addInitScript(()=>sessionStorage.setItem('fdc-guard-ok','1'));const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));
for(const name of names){await page.goto(base+name+'.html');if(name!=='vyrazy'){assert.match(await page.locator('#expression').textContent(),/[xy]/);assert.match(await page.locator('#rule').textContent(),/Zjednoduš/);assert.match(await page.locator('#algebraTopics').textContent(),/Slučování/);}if(name==='mnohocleny')assert.match(await page.locator('#formulaStrip').textContent(),/a² − b²/);await page.locator('#practice').click();const topicCount=await page.locator('#topic option').count();for(let t=0;t<topicCount;t++)for(let l=0;l<3;l++){await page.locator('#topic').selectOption(String(t));await page.locator('#level').selectOption(String(l));await solve(page);await page.locator('#next').click();}await page.screenshot({path:'test-results/'+name+'-desktop.png',fullPage:true});await page.locator('#parentButton').click();await page.locator('#parentPassword').fill('matematika123');await page.locator('#parentUnlock').click();await page.locator('#parentActions').waitFor();assert.match(await page.locator('#parentData').textContent(),/Chybné pokusy/);await page.locator('#parentClose').click();await page.locator('#parentButton').click();await page.locator('#parentPassword').fill('spatneHeslo');await page.locator('#parentUnlock').click();await page.waitForFunction(()=>document.querySelector('#parentInfo').textContent.includes('Nesprávné'));assert.equal(await page.locator('#parentActions').isVisible(),false);await page.locator('#parentClose').click();}
// A genuine algebraic intermediate remains incomplete, is recorded, and is not a wrong attempt.
await page.goto(base+'vyrazy-promenne.html');await page.locator('#topic').selectOption('0');await page.locator('#level').selectOption('0');await page.locator('#teach').click();const beforeStep=await page.evaluate(()=>ExpressionApp.getState());const expansion=await page.evaluate(()=>ExpressionContent.algebraDerivation(ExpressionApp.getState().task.expression).expanded);await page.locator('#answer').fill(expansion);await page.locator('#check').click();assert.equal(await page.evaluate(()=>ExpressionApp.getState().finished),false);assert.equal(await page.evaluate(()=>ExpressionApp.getState().stats.wrong),beforeStep.stats.wrong);assert(await page.locator('#workSteps').isVisible());assert.match(await page.locator('#feedback').textContent(),/mez.*krok/);await solve(page);await page.keyboard.press('Enter');
// Retrying, hints, skip accounting, next on Enter and teaching progression.
await page.goto(base+'vyrazy.html');await page.locator('#topic').selectOption('0');await page.locator('#level').selectOption('0');await page.locator('#teach').click();for(let i=0;i<3;i++){await solve(page);await page.keyboard.press('Enter')}assert.match(await page.locator('#phase').textContent(),/Princip ověřen/);await page.locator('#practice').click();for(let i=0;i<2;i++){await page.locator('#answer').fill('999999999');await page.locator('#check').click()}assert.match(await page.locator('#feedback').textContent(),/nápovědu/);await page.locator('#hint').click();await page.locator('#answer').fill('999999999');await page.locator('#check').click();assert(await page.locator('#explain').isVisible());await page.keyboard.press('Enter');const before=await page.evaluate(()=>ExpressionApp.getState().stats.skips);await page.locator('#skip').click();assert.equal(await page.evaluate(()=>ExpressionApp.getState().stats.skips),before+1);
await page.keyboard.press('Enter');await page.locator('#answer').fill('x');await page.locator('#power').click();assert.equal(await page.locator('#answer').inputValue(),'x^2');await page.locator('#theme').click();assert.equal(await page.locator('body').getAttribute('data-theme'),'dark');await page.screenshot({path:'test-results/dark.png',fullPage:true});await page.locator('#sound').click();assert.match(await page.locator('#sound').textContent(),/vypnutý/);await page.locator('#game').click();assert.equal(await page.locator('#world').isVisible(),false);await page.locator('#game').click();
await page.locator('#parentButton').click();await page.locator('#parentPassword').fill('matematika123');await page.locator('#parentUnlock').click();await page.locator('#parentActions').waitFor();await page.locator('[data-target]').first().click();assert(await page.locator('#exercise').isVisible());assert.equal(await page.evaluate(()=>ExpressionApp.getState().sel.mode),'practice');await page.locator('#parentButton').click();await page.locator('#parentPassword').fill('matematika123');await page.locator('#parentUnlock').click();await page.locator('#parentActions').waitFor();page.once('dialog',d=>d.accept());await page.locator('#parentReset').click();await page.locator('#parentClose').click();assert.equal(await page.evaluate(()=>ExpressionApp.getState().stats.done),0);
const stored=await page.evaluate(()=>JSON.stringify(localStorage));assert(!stored.includes('matematika123'),'plaintext password');
assert.equal(errors.length,0,errors.join('\n'));console.log(`PASS: ${solved} UI solutions, every topic/difficulty, three demo limits/reloads, guard redirects, parent setup/denial/reset/target practice, teaching progression, retries/hints/skips, powers, themes, sound/game toggle, mobile layout. No page errors.`);await ctx.close();
}finally{await browser.close()}
